spring.application.name=gerenciamento-usuario

# URL de conexão com MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/api

# Credenciais
spring.datasource.username=root
spring.datasource.password=

# Driver JDBC do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialeto do Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Atualiza automaticamente as tabelas
spring.jpa.hibernate.ddl-auto=update

# Exibe SQL no console
spring.jpa.show-sql=true

# Formata SQL
spring.jpa.properties.hibernate.format_sql=true